on:
  workflow_call:
    inputs:
      rollapp_evm_ci:
        description: "CI run on Rollapp-EVM Repo"
        required: false
        type: string
        default: "latest"
      upgrade_name:
        description: "Upgrade Name be used by e2e-tests"
        required: true
        type: string
        default: ""

jobs:
  # e2e-tests-by runs the actual go test command to trigger the test.
  rollapp-evm-upgrade:
    strategy:
      matrix:
        tests:
          - "e2e-test-rollapp-upgrade-evm"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
          ref: main
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: e2e
          path: /tmp

      - name: Load Docker Image
        run: |
          docker image load -i /tmp/e2e.tar 
          docker image ls -a

      - name: Rollapp-EVM Upgrade E2E Tests
        run: make ${{ matrix.tests }}
        env:
          DYMENSION_CI: ${{ inputs.rollapp_evm_ci }}
          UPGRADE_ROLLAPP_EVM_NAME: ${{ inputs.upgrade_name }}