on:
    workflow_call:
      inputs:
        rollapp_wasm_ci:
          description: "CI run on Rollapp-Wasm Repo"
          required: false
          type: string
          default: "latest"
  
jobs:
    # e2e-tests-by runs the actual go test command to trigger the test.
    rollapp-wasm:
      strategy:
        matrix:
          tests:
            - "e2e-test-ibc-success-wasm"
            - "e2e-test-ibc-timeout-wasm"
            - "e2e-test-ibc-grace-period-wasm"
            - "e2e-test-eibc-fulfillment-wasm"
            - "e2e-test-eibc-fulfillment-thirdparty-wasm"
            - "e2e-test-eibc-pfm-wasm"
            - "e2e-test-transfer-multi-hop-wasm"
            - "e2e-test-pfm-with-grace-period-wasm"
            - "e2e-test-pfm-gaia-to-rollapp-wasm"
            - "e2e-test-batch-finalization-wasm"
            - "e2e-test-disconnection-wasm"
            - "e2e-test-rollapp-freeze-wasm"
            - "e2e-test-other-rollapp-not-affected-wasm"
            - "e2e-test-delayedack-pending-packets-wasm"
            - "e2e-test-delayedack-relayer-down-wasm"
            - "e2e-test-pfm-with-grace-period-rollapp1-to-rollapp2-without-erc20"
        fail-fast: false
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            repository: dymensionxyz/e2e-tests
        - name: Set up Go 1.21
          uses: actions/setup-go@v4
          with:
            go-version: "1.21.4"
  
        - name: Download Tarball Artifact
          uses: actions/download-artifact@v3
          with:
            name: e2e
            path: /tmp
  
        - name: Load Docker Image
          run: |
            docker image load -i /tmp/e2e.tar 
            docker image ls -a
  
        - name: Rollapp-Wasm E2E Tests
          run: make ${{ matrix.tests }}
          env:
            ROLLAPP_WASM_CI: ${{ inputs.rollapp_wasm_ci }}
  