on:
  workflow_call:
    inputs:
      dymension_ci:
        description: "CI run on Dymension Repo"
        required: false
        type: string
        default: "latest"
      relayer_ci:
        description: "CI run on Relayer Repo"
        required: false
        type: string
        default: "main-dym"
      upgrade_name:
        description: "Upgrade Name be used by e2e-tests"
        required: false
        type: string
        default: ""

jobs:
  # e2e-tests-by runs the actual go test command to trigger the test.
  hub-upgrade:
    strategy:
      matrix:
        tests:
          - "e2e-test-upgrade-hub"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
          ref: main
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: e2e
          path: /tmp

      - name: Load Docker Image
        run: |
          docker image load -i /tmp/e2e.tar 
          docker image ls -a

      - name: Upgrade Hub E2E Tests
        run: sudo -E make ${{ matrix.tests }} 
        env:
          DYMENSION_CI: ${{ inputs.dymension_ci }}
          UPGRADE_NAME: ${{ inputs.upgrade_name }}
          RELAYER_CI: ${{ inputs.relayer_ci }}