name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

permissions:
  contents: read
  packages: write

jobs:
  # e2e-tests-by runs the actual go test command to trigger the test.
  e2e-tests:
    strategy:
      matrix:
        tests:
          - "e2e-test-ibc-success"
          - "e2e-test-ibc-timeout"
          - "e2e-test-ibc-grace-period"
          - "e2e-test-eibc-fulfillment"
          - "e2e-test-transfer-multi-hop"
          - "e2e-test-pfm-with-grace-period"
          - "e2e-test-batch-finalization"
          - "e2e-test-rollapp-freeze"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: E2E Tests
        run: |
          make ${{ matrix.tests }}
