name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"
      - "live-tests/**"

permissions:
  contents: read
  packages: write

jobs:
  build-evm-matrix:
    runs-on: ubuntu-latest-m
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - id: set-matrix
        run: |
          output=$(go run build_tests_matrix/main.go)
          echo "matrix=$output" >> $GITHUB_OUTPUT
        env:
          ROLLAPP_TYPE: "EVM"
  build-wasm-matrix:
    runs-on: ubuntu-latest-m
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - id: set-matrix
        run: |
          output=$(go run build_tests_matrix/main.go)
          echo "matrix=$output" >> $GITHUB_OUTPUT
        env:
          ROLLAPP_TYPE: "Wasm"
  # e2e-tests-by runs the actual go test command to trigger the test.
  rollapp-evm:
    needs:
      - build-evm-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-evm-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Rollapp-EVM E2E Tests
        run: sudo make e2e-test test=${{ matrix.test }}

  # e2e-tests-by runs the actual go test command to trigger the test.
  rollapp-wasm:
      needs:
        - build-wasm-matrix
      strategy:
        fail-fast: false
        matrix: ${{ fromJSON(needs.build-wasm-matrix.outputs.matrix) }}
      runs-on: ubuntu-latest-m
      steps:
        - uses: actions/checkout@v4
          with:
            repository: dymensionxyz/e2e-tests
        - name: Set up Go 1.21
          uses: actions/setup-go@v4
          with:
            go-version: "1.21.4"
  
        - name: Rollapp-Wasm E2E Tests
          run: sudo make e2e-test test=${{ matrix.test }}
