name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

permissions:
  contents: read
  packages: write

jobs:
  # e2e-tests-by runs the actual go test command to trigger the test.
  rollapp-evm:
    strategy:
      matrix:
        tests:
          - "e2e-test-ibc-success-evm"
          - "e2e-test-ibc-timeout-evm"
          - "e2e-test-ibc-grace-period-evm"
          - "e2e-test-eibc-fulfillment-evm-2-RAs"
          - "e2e-test-eibc-corrupted-memo-evm"
          - "e2e-test-eibc-excessive-fee-evm"
          - "e2e-test-eibc-fulfillment-evm"
          - "e2e-test-eibc-fulfillment-ignore-hub-to-rollapp-evm"
          - "e2e-test-eibc-fulfill-no-balance-evm"
          - "e2e-test-eibc-fulfillment-thirdparty-evm"
          - "e2e-test-eibc-pfm-evm"
          - "e2e-test-eibc-timeout-evm"
          - "e2e-test-eibc-timeout_and_fulfill-evm"
          - "e2e-test-eibc-not-fulfillment-evm"
          - "e2e-test-transfer-multi-hop-evm"
          - "e2e-test-pfm-with-grace-period-evm"
          - "e2e-test-pfm-with-grace-period-rollapp1-to-rollapp2-erc20"
          - "e2e-test-pfm-gaia-to-rollapp-evm"
          - "e2e-test-batch-finalization-evm"
          - "e2e-test-disconnection-evm"
          - "e2e-test-rollapp-freeze-evm"
          - "e2e-test-other-rollapp-not-affected-evm"
          - "e2e-test-rollapp-genesis-event-evm"
          - "e2e-test-dym-finalize-block-on-recv-packet-evm"
          - "e2e-test-dym-finalize-block-on-timeout-packet-evm"
          - "e2e-test-dym-finalize-block-on-ack-packet-evm"
          - "e2e-test-delayedack-pending-packets-evm"
          - "e2e-test-delayedack-relayer-down-evm"
          - "e2e-test-sequencer-invariant-evm"
          - "e2e-test-rollapp-invariant-evm"
          - "e2e-test-eibc-invariant-evm"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Rollapp-EVM E2E Tests
        run: |
          make ${{ matrix.tests }}
  rollapp-wasm:
    strategy:
      matrix:
        tests:
          - "e2e-test-ibc-success-wasm"
          - "e2e-test-ibc-timeout-wasm"
          - "e2e-test-ibc-grace-period-wasm"
          - "e2e-test-eibc-fulfillment-wasm"
          - "e2e-test-eibc-fulfillment-ignore-hub-to-rollapp-wasm"
          - "e2e-test-eibc-fulfillment-thirdparty-wasm"
          - "e2e-test-eibc-pfm-wasm"
          - "e2e-test-eibc-timeout_and_fulfill-wasm"
          - "e2e-test-eibc-not-fulfillment-wasm"
          - "e2e-test-transfer-multi-hop-wasm"
          - "e2e-test-pfm-with-grace-period-wasm"
          - "e2e-test-pfm-gaia-to-rollapp-wasm"
          - "e2e-test-batch-finalization-wasm"
          - "e2e-test-disconnection-wasm"
          - "e2e-test-rollapp-freeze-wasm"
          - "e2e-test-other-rollapp-not-affected-wasm"
          - "e2e-test-dym-finalize-block-on-recv-packet-wasm"
          - "e2e-test-dym-finalize-block-on-timeout-packet-wasm"
          - "e2e-test-dym-finalize-block-on-ack-packet-wasm"
          - "e2e-test-delayedack-pending-packets-wasm"
          - "e2e-test-delayedack-relayer-down-wasm"
          - "e2e-test-rollapp-invariant-wasm"
          - "e2e-test-eibc-invariant-wasm"
          - "e2e-test-pfm-with-grace-period-rollapp1-to-rollapp2-without-erc20"
          - "e2e-test-sequencer-invariant-wasm"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dymensionxyz/e2e-tests
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.4"

      - name: Rollapp-Wasm E2E Tests
        run: make ${{ matrix.tests }}
