name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'

permissions:
  contents: read
  packages: write

jobs:   
  e2e-tests:
    uses: ./github/workflows/e2e-test-workflow-call.yml@main
